# Generated by Django 4.2.8 on 2026-09-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Skill name (e.g., 'Python')", max_length=100)),
                ('icon_url', models.URLField(help_text='URL to the skill icon image', max_length=500)),
                ('color', models.CharField(default='#667eea', help_text="Brand color hex (e.g., '#3776AB')", max_length=7)),
                ('proficiency', models.PositiveIntegerField(default=0, help_text='Proficiency percentage (0-100)')),
                ('description', models.TextField(help_text='Short description of the skill')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Skill',
                'verbose_name_plural': 'Homepage Skills',
                'ordering': ['order', 'name'],
            },
        ),
    ]
